export const categoryNames: { [key: string]: string } = {
  auto: "Авто",
  "business-and-services": "Бізнес та послуги",
  "for-free": "Безкоштовно",
  "children's-world": "Дитячий світ",
  "home-and-garden": "Дім і сад",
  help: "Допомога",
  electronics: "Електроніка",
  "spare-parts-for-transport": "Запчастини для транспорту",
  "fashion-and-style": "Мода і стиль",
  realty: "Нерухомість",
  exchange: "Обмін",
  repair: "Ремонт",
  work: "Робота",
  animals: "Тварини",
  "goods-to-win": "Товари для перемоги",
  "hobbies-recreation-sports": "Хобі, відпочинок і спорт",
};
